- name: Provision Swift Cluster
  hosts: local
  connection: local
  gather_facts: false

  vars:
    credentials: ~/.rackspace_cloud_credentials
    pub_key: ~/.ssh/id_rsa.pub
    region: IAD
    flavor: 3
    image: e0ed4adb-3a00-433e-a0ac-a51f1bc1ea3d
    meta:
      group: swift

  tasks:

    - name: Create Isolated Network
      local_action:
        module: rax_network
        credentials: $credentials
        label: swift_network
        region: $region
        cidr: 192.168.122.0/24
        state: present
      register: swift_network

    - name: Provision Chef Server
      local_action:
        module: rax_server
        credentials: $credentials
        service: cloudservers
        name: swift-chef-server
        flavor: $flavor
        image: $image
        region: $region
        meta: $meta
        nics:
          - net-id: 00000000-0000-0000-0000-000000000000
          - net-id: 11111111-1111-1111-1111-111111111111
          - net-id: "{{ swift_network.instances[0].id }}"
        files:
          /root/.ssh/authorized_keys: $pub_key
        wait: yes
        state: present
      register: swift_chef_server

    - name: Provision Management Server
      local_action:
        module: rax_server
        credentials: $credentials
        service: cloudservers
        name: swift-management-server
        flavor: $flavor
        image: $image
        region: $region
        meta: $meta
        nics:
          - net-id: 00000000-0000-0000-0000-000000000000
          - net-id: 11111111-1111-1111-1111-111111111111
          - net-id: "{{ swift_network.instances[0].id }}"
        files:
          /root/.ssh/authorized_keys: $pub_key
        wait: yes
        state: present
      register: swift_management_server

    - name: Provision Storage Servers
      local_action:
        module: rax_server
        credentials: $credentials
        service: cloudservers
        name: swift-storage-server-$item
        flavor: $flavor
        image: $image
        region: $region
        meta: $meta
        nics:
          - net-id: 00000000-0000-0000-0000-000000000000
          - net-id: 11111111-1111-1111-1111-111111111111
          - net-id: "{{ swift_network.instances[0].id }}"
        files:
          /root/.ssh/authorized_keys: $pub_key
        wait: yes
        state: present
      with_sequence: count=3
      register: swift_storage_servers

    - name: Provision Proxy Servers
      local_action:
        module: rax_server
        credentials: $credentials
        service: cloudservers
        name: swift-proxy-server-$item
        flavor: $flavor
        image: $image
        region: $region
        meta: $meta
        nics:
          - net-id: 00000000-0000-0000-0000-000000000000
          - net-id: 11111111-1111-1111-1111-111111111111
          - net-id: "{{ swift_network.instances[0].id }}"
        files:
          /root/.ssh/authorized_keys: $pub_key
        wait: yes
        state: present
      with_sequence: count=2
      register: swift_proxy_servers

    - name: Create Inventory File
      local_action:
        module: template
        src: rackspace_inventory.j2
        dest: ../rackspace
