- include: chef-server.yml
- include: chef-clients.yml
- include: management-server.yml
- include: proxy-servers.yml
- include: storage-servers.yml
- include: management-server.yml
- include: proxy-servers.yml
