- name: Drop Client JSON
  template: src=./etc/chef/chef-client.json.j2 dest=/etc/chef/chef-client.json

- name: Chef Management Role
  shell: chef-client -o "role[spc-starter-controller]" -j "/etc/chef/chef-client.json"
