- name: Install Chef Client
  shell: curl -skS -L http://www.opscode.com/chef/install.sh | bash creates=/opt/chef

- name: Add Chef Server Hosts Entry
  action: host ip={{ item }} hostname={{ hostvars[item]['ansible_hostname'] }} state=present
  with_items: groups['chef-server'][0]

- name: Create Chef Client Directory
  shell: mkdir -p /etc/chef creates=/etc/chef

- name: Upload Validation Key
  local_action: shell scp -B -C -q -v ./tmp/chef-validator.pem root@{{ inventory_hostname }}:/etc/chef/validation.pem

- name: Configure Chef Client
  template: src=./etc/chef/client.rb.j2 dest=/etc/chef/client.rb

- name: Register Chef Client
  shell: chef-client creates=/etc/chef/client.pem
