- name: Set Private Network Facts
  set_fact:
    chef_server_address: "{{ hostvars[groups['chef-server'][0] ].ansible_eth2.ipv4.address }}"
    chef_server_hostname: "{{ hostvars[ groups['chef-server'][0] ].ansible_hostname }}"

- name: Install Chef Client
  shell: curl -skS -L http://www.opscode.com/chef/install.sh | bash -s -- -v 11.8.2 creates=/opt/chef

- name: Add Chef Server Hosts Entry
  action: host ip={{ chef_server_address }} hostname={{ chef_server_hostname }} state=present

- name: Create Chef Client Directory
  shell: mkdir -p /etc/chef creates=/etc/chef

- name: Upload Validation Key
  copy:
    src: "{{ inventory_dir }}/tmp/chef-validator.pem/{{ groups['chef-server'][0] }}/etc/chef-server/chef-validator.pem"
    dest: /etc/chef/validation.pem

- name: Configure Chef Client
  template:
    src: ./etc/chef/client.rb.j2
    dest: /etc/chef/client.rb

- name: Register Chef Client
  shell: chef-client creates=/etc/chef/client.pem
