- name: Create Isolated Network
  rax_network:
    credentials: ${rackspace.credentials}
    label: swift_network
    region: ${rackspace.region}
    cidr: 192.168.122.0/24
    state: present
  register: swift_network

- name: Provision Chef Server
  rax_server:
    credentials: ${rackspace.credentials}
    name: ${prefix}swift-chef-server
    flavor: ${rackspace.flavor}
    image: ${rackspace.image}
    region: ${rackspace.region}
    meta: ${rackspace.meta}
    nics:
      - net-id: 00000000-0000-0000-0000-000000000000
      - net-id: 11111111-1111-1111-1111-111111111111
      - net-id: "{{ swift_network.instances[0].id }}"
    files:
      /root/.ssh/authorized_keys: ${rackspace.pub_key}
    wait: yes
    state: present
  register: swift_chef_server

- name: Provision Management Server
  rax_server:
    credentials: ${rackspace.credentials}
    name: ${prefix}swift-management-server
    flavor: ${rackspace.flavor}
    image: ${rackspace.image}
    region: ${rackspace.region}
    meta: ${rackspace.meta}
    nics:
      - net-id: 00000000-0000-0000-0000-000000000000
      - net-id: 11111111-1111-1111-1111-111111111111
      - net-id: "{{ swift_network.instances[0].id }}"
    files:
      /root/.ssh/authorized_keys: ${rackspace.pub_key}
    wait: yes
    state: present
  register: swift_management_server

- name: Provision Storage Servers
  rax_server:
    credentials: ${rackspace.credentials}
    name: ${prefix}swift-storage-server-${item}
    disk_config: manual
    flavor: ${rackspace.flavor}
    image: ${rackspace.image}
    region: ${rackspace.region}
    meta: ${rackspace.meta}
    nics:
      - net-id: 00000000-0000-0000-0000-000000000000
      - net-id: 11111111-1111-1111-1111-111111111111
      - net-id: "{{ swift_network.instances[0].id }}"
    files:
      /root/.ssh/authorized_keys: ${rackspace.pub_key}
    wait: yes
    state: present
  with_sequence: count=${storage_server.count}
  register: swift_storage_servers

- name: Provision Proxy Servers
  rax_server:
    credentials: ${rackspace.credentials}
    name: ${prefix}swift-proxy-servers-${item}
    flavor: ${rackspace.flavor}
    image: ${rackspace.image}
    region: ${rackspace.region}
    meta: ${rackspace.meta}
    nics:
      - net-id: 00000000-0000-0000-0000-000000000000
      - net-id: 11111111-1111-1111-1111-111111111111
      - net-id: "{{ swift_network.instances[0].id }}"
    files:
      /root/.ssh/authorized_keys: ${rackspace.pub_key}
    wait: yes
    state: present
  with_sequence: count=${proxy_server.count}
  register: swift_proxy_servers

- name: Create Inventory File
  template:
    src: inventory.j2
    dest: ./${prefix}${rackspace.inventory}-${rackspace.env}
