- name: Disable Firewall
  service: name=iptables state=stopped
  when: ansible_os_family == 'RedHat'

- name: Install Chef Server
  shell: curl -s -L https://raw.github.com/rcbops/support-tools/master/chef-install/install-chef-server.sh | bash creates=~/.chef/knife.rb

- name: Download Validaton Key
  fetch:
    src: /etc/chef-server/chef-validator.pem
    dest: ./tmp/chef-validator.pem

- name: Download EPEL Repo RPM
  get_url: dest=/tmp/epel-release-6-8.noarch.rpm  url=http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  when: ansible_os_family == 'RedHat'

- name: Install EPEL Repo RPM
  yum: pkg=/tmp/epel-release-6-8.noarch.rpm state=installed
  when: ansible_os_family == 'RedHat'

- name: Install Berkshelf
  shell: /opt/chef-server/embedded/bin/gem install berkshelf creates=/opt/chef-server/embedded/bin/berks

- name: Checkout Cookbooks
  git: repo={{ git.url }} dest={{ git.dest }} version={{ git.version }}

- name: Berkshelf Install Dependencies
  shell: /opt/chef-server/embedded/bin/berks install -p ../cookbooks chdir={{ git.dest }}

- name: Upload Chef Environments
  shell: /opt/chef-server/embedded/bin/knife environment from file ./environments/*.rb chdir={{ git.dest }}

- name: Upload Chef Roles
  shell: /opt/chef-server/embedded/bin/knife role from file ./roles/*.rb chdir={{ git.dest }}

- name: Upload Chef Cookbooks
  shell: /opt/chef-server/embedded/bin/knife cookbook upload --all -o . chdir=/srv/cookbooks
